---
title: "Tytuł raportu"
subtitle: "Podtytuł"
author: "Imię Nazwisko"
date: today
lang: pl
bibliography: bibliografia.bib
csl: apa.csl
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Spis treści"
    number-sections: true
    theme: cosmo
    embed-resources: true
    code-fold: true
    code-summary: "Pokaż kod"
    fig-width: 7
    fig-height: 4.5
  docx:
    toc: true
    number-sections: true
    fig-width: 6
    fig-height: 4
execute:
  echo: false
  warning: false
  message: false
---

```{r}
#| label: setup_09
#| include: false

library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)

# Wczytanie danych
# dane <- read_csv("dane.csv")
```

## Wstęp

Krótki opis celu raportu, źródła danych i okresu analizy.
Dane pochodzą z bazy [@zrodlo2024].

## Dane i metodologia {#sec-dane}

Opis zbioru danych i zastosowanych metod.

## Wyniki analizy {#sec-wyniki}

### Statystyki opisowe


```{r}
#| label: tbl-statystyki
#| tbl-cap: "Podstawowe statystyki opisowe"

# dane |>
#   summary() |>
#   kable(digits = 2) |>
#   kable_styling(bootstrap_options = "striped")
```

### Wykres

```{r}
#| label: fig-glowny
#| fig-cap: "Tytuł wykresu"
#| fig-width: 8
#| fig-height: 5

# ggplot(dane, aes(...)) + geom_...()
```

Jak pokazano na @fig-glowny, ...

## Wnioski

Podsumowanie najważniejszych wyników.

## Literatura

::: {#refs}
:::